name: Upload Dataset to Hugging Face Hub

on:
  push:
    branches:
      - main  

jobs:
  upload-dataset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install huggingface_hub

      - name: Upload CSV to Hugging Face Hub (as Dataset)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          import os
          from huggingface_hub import HfApi
          
          api = HfApi()
          repo_id = "Ataur77/customer-query-classify"
          token = os.environ["HF_TOKEN"]

          # Create dataset repo (type='dataset')
          api.create_repo(repo_id=repo_id, repo_type="dataset", exist_ok=True, token=token)

          # Upload folder (or single file)
          api.upload_file(
              path_or_fileobj="data/customer_queries.csv",  
              path_in_repo="customer_queries.csv",
              repo_id=repo_id,
              repo_type="dataset",
              token=token
          )

          # Optional: upload README
          if os.path.exists("README.md"):
              api.upload_file(
                  path_or_fileobj="README.md",
                  path_in_repo="README.md",
                  repo_id=repo_id,
                  repo_type="dataset",
                  token=token
              )
        shell: python
